import React from 'react';
import { Document, Page, View, StyleSheet, Image, Text } from '@react-pdf/renderer';

// Create styles
const styles = StyleSheet.create({
  page: {
    backgroundColor: '#fff',
    padding: '80px 40px 50px 40px',
    fontSize: '10px',
    fontWeight: 'thin',
    display: 'flex',
  },
});

// Wraps a plain string onto multiple lines for the fixed-width PDF box —
// only used for RFID/NFC, which have no image (nothing physical to scan),
// so the raw code value is the only thing there is to print for them.
const splitText = (text) => {
  const str = String(text || '');
  const parts = [];
  for (let i = 0; i < Math.ceil(str.length / 15); i++) {
    parts.push(str.substr(i * 15, 15));
  }
  return parts;
};

// A4 page is 595pt wide; styles.page pads 40pt each side, leaving ~515pt of
// content width to divide across however many items go in one row.
const PAGE_CONTENT_WIDTH = 515;
const ITEM_MARGIN = 6;

/**
 * Props-driven PDF document. The QR/barcode images are pre-generated by the
 * caller and passed in (`items: [{ img, code }]`), so the document never
 * renders an empty <Image> — which previously produced a blank PDF when the
 * async image generation hadn't completed before react-pdf built the blob.
 * Prints the code only — the image when there is one (QR, Security QR,
 * GS1 Digital Link, Barcode), or else just the bare code value as text
 * (RFID/NFC, which have no visual code) — no PMC codes, labels, or other
 * identifier text alongside it. `itemsPerRow` controls how many items fit
 * across one line (see PrintDialog's "Items per row" field).
 */
const MyDocument = ({ items = [], itemsPerRow = 5 }) => {
  const perRow = Math.max(1, Number(itemsPerRow) || 5);
  const itemSize = Math.max(30, Math.floor(PAGE_CONTENT_WIDTH / perRow) - ITEM_MARGIN * 2);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={{ display: 'flex', flexDirection: 'row', flexWrap: 'wrap' }}>
          {items.map((it, index) => (
            <View key={index} style={{ width: `${itemSize}px`, margin: `${ITEM_MARGIN}px` }}>
              {it.img ? (
                <Image src={it.img} style={{ width: `${itemSize}px`, height: `${itemSize}px` }} />
              ) : (
                it.code && splitText(it.code).map((line, k) => (
                  <Text key={k} style={{ fontSize: 12, color: 'black' }}>{line}</Text>
                ))
              )}
            </View>
          ))}
        </View>
      </Page>
    </Document>
  );
};

export default MyDocument;
