import React from 'react';
import { Document, Page, View, StyleSheet, Image, Text } from '@react-pdf/renderer';

// Create styles
const styles = StyleSheet.create({
  page: {
    backgroundColor: '#fff',
    padding: '80px 40px 50px 40px',
    fontSize: '10px',
    fontWeight: 'thin',
    display: 'flex',
  },
});

const splitIdentifier = (item) => {
  const text = `${item.type} : ${item.serial}`;
  const parts = [];
  for (let i = 0; i < Math.round(text.length / 15); i++) {
    parts.push(text.substr(i * 15, 15));
  }
  return parts;
};

/**
 * Props-driven PDF document. The QR images are pre-generated by the caller and
 * passed in (`items: [{ img, identifiers }]`), so the document never renders an
 * empty <Image> — which previously produced a blank PDF when the async QR image
 * generation hadn't completed before react-pdf built the blob.
 */
const MyDocument = ({ items = [] }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={{ display: 'flex', flexDirection: 'row', flexWrap: 'wrap' }}>
        {items.map((it, index) => (
          <View key={index} style={{ maxWidth: '100px', margin: '6px' }}>
            {!!it.img && <Image src={it.img} style={{ width: '100px', height: '100px' }} />}
            <View>
              {(it.identifiers || []).map((item, j) => (
                <View key={j}>
                  {splitIdentifier(item).map((info, k) => (
                    <Text key={k} style={{ fontSize: 12, color: 'black' }}>{info}</Text>
                  ))}
                </View>
              ))}
            </View>
          </View>
        ))}
      </View>
    </Page>
  </Document>
);

export default MyDocument;
